---

- name: Converge
  hosts: all
  gather_facts: no


  pre_tasks:
    - name: Bootstrap Python 3 if missing (raw)
      ansible.builtin.raw: >
        bash -lc '
        if ! command -v python3 >/dev/null 2>&1; then
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update -y && apt-get install -y python3;
          elif command -v dnf >/dev/null 2>&1; then
            dnf -y install python3 || dnf -y install python39;
          elif command -v yum >/dev/null 2>&1; then
            yum -y install python3 || yum -y install python36;
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache python3;
          fi
        fi'
      changed_when: false

    - name: Create temp directory (raw)
      ansible.builtin.raw: >
        bash -lc 'mkdir -p /tmp/ansible-tmp && chmod 0777 /tmp/ansible-tmp'
      changed_when: false

    - name: Reset connection to pick up Python
      ansible.builtin.meta: reset_connection

  roles:
    - role: iamenr0s.ansible_role_users
      # You can create groups:
      users_groups:
        - name: mygroup
          gid: 1024
        - name: users
        # You can also remove groups.
        - name: notgroup
          state: absent
          # A system group is also possible.
        - name: systemgroup
          system: true
      # You can create users.
      users:
        - name: myuser
          comment: My User
          uid: 1024
          manage_ssh_key: true
          # The `group` and `groups` listed here should exist.
          group: mygroup
          # groups: A list of groups
          # groups:
          #   - users
          #   - wheel
          groups:
            - users
          sudo_options: "ALL=(ALL) NOPASSWD: ALL"
          # Adding an authorized key.
          authorized_keys:
            - "ssh-rsa ABC123"
          expires: -1
          password_validity_days: 9
          # Test username with dots
        # Here a user is removed.
        - name: notuser
          state: absent
        - name: keyuser
          manage_ssh_key: true
        - name: privkeyuser
          # This user will have ssh-keys generated.
          manage_ssh_key: true
          copy_private_key: true
        - name: multiplekeys
          authorized_keys:
            - "ssh-rsa ABC1234"
            - "ssh-rsa ABC12345"
        - name: passuser
          # You can set a password. (Hashed and salted.)
          password: "$6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1"
          update_password: on_create
        - name: remotekey
          authorized_keys:
            # You can also download a public key from a URL.
            - "https://raw.githubusercontent.com/shaanr/smdb/master/file.pub"
        - name: systemuser
          system: true
        - name: multisudo
          # An account that can run just a few commands without a password.
          sudo_options:
            - "ALL= NOPASSWD: /usr/bin/systemctl restart httpd"
            - "ALL= NOPASSWD: /usr/bin/systemctl start httpd"
            - "ALL= NOPASSWD: /usr/bin/systemctl stop httpd"
        - name: myprivkeyuser
          private_keys:
            - name: id_rsa
              content: |
                -----BEGIN OPENSSH PRIVATE KEY-----
                ...
                ...
                -----END OPENSSH PRIVATE KEY-----
