---
- name: Prepare
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Ensure /tmp exists (raw)
      ansible.builtin.raw: >
        bash -lc 'mkdir -p /tmp && chmod 0777 /tmp'
      changed_when: false

    - name: Install Python 3 (raw, cross-platform)
      ansible.builtin.raw: >
        bash -lc '
        if command -v dnf >/dev/null 2>&1; then
          dnf -y install python39 || dnf -y install python3;
        elif command -v yum >/dev/null 2>&1; then
          yum -y install python3 || yum -y install python36;
        elif command -v apt-get >/dev/null 2>&1; then
          apt-get update -y && apt-get install -y python3;
        elif command -v apk >/dev/null 2>&1; then
          apk add --no-cache python3;
        fi'
      changed_when: true

    - name: Prefer Python 3.9 if available
      ansible.builtin.raw: >
        bash -lc 'if [ -x /usr/bin/python3.9 ]; then ln -sf /usr/bin/python3.9 /usr/bin/python3; fi'
      changed_when: false

    - name: Reset connection to use installed Python
      ansible.builtin.meta: reset_connection